kind: pipeline
type: kubernetes
name: Build and Deploy Website
node_selector:
  kubernetes.io/arch: amd64

platform:
  os: linux
  arch: arm64

workspace:
  path: /drone/src

steps:
  - name: generate files
    image: node:16-slim
    commands:
      - apk add --no-cache autoconf automake libtool make tiff jpeg zlib zlib-dev pkgconf nasm file gcc musl-dev
      - npm install
      - npm run export
  - name: sync server
    image: eeacms/rsync:latest
    environment:
      NFS_DIRECTORY: 
        from_secret: NFS_DIRECTORY
    volumes:
      - name: nfs
        path: /dest
    commands:
      - rsync -avzr --delete dist/ /dest/${NFS_DIRECTORY}/

volumes:
  - name: nfs
    host:
      path: /mnt/nfs
