kind: pipeline
type: kubernetes
name: Build and Deploy Website
node_selector:
  kubernetes.io/arch: amd64

platform:
  os: linux
  arch: arm64

workspace:
  path: /drone/src

steps:
  - name: generate files
    image: node:16-alpine
    commands:
      - apk add --no-cache autoconf automake
      - npm ci
      - npm run export
  - name: sync server
    image: eeacms/rsync:latest
    environment:
      NFS_DIRECTORY: 
        from_secret: NFS_DIRECTORY
    volumes:
      - name: data
        path: /src
      - name: nfs
        path: /dest
    commands:
      - rsync -avzr --delete dist/ /src/${NFS_DIRECTORY}

services:
  - name: mount nfs
    image: d3fk/nfs-client:latest
    environment:
      MOUNTPOINT: /nfs
      FSTYPE: nfs4
      SERVER: 
        from_secret: NFS_SERVER
      SHARE: 
        from_secret: NFS_SHARE
    volumes:
      - name: nfs
        path: /nfs

volumes:
  - name: nfs
    temp: {}
