language: node_js
node_js:
  - 14

script:
  - npm run generate

before_deploy:
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
    -in deploy/deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - echo -e "Host ${DEPLOY_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --quiet --delete ${TRAVIS_BUILD_DIR}/dist/ ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIRECTORY}
  on:
    branch: master

env:
  global:
    - secure: McBT6nTMQxiZ8dbbBYa/aSt+sEf/77x6XoxJMiZ+zltQKUcOxTxETTPBRmzEeZZC1rdyronR1T3JgdWRIV7r9jQ3QpQXi8VNV4/TQ9BhhSVbkVnxnfKzO571dmNbUXKwS0zCi9i95qyr7M2mIVdRUCGsZWZmxnKWUGforAeDgFOLii21wQI+BPOmXugw5F9+JzZZsfKpwGMZkjoLo5JJpdausklDxNPBxtDUXXiz28wQzjCKPZB20S1hxgNKaOSrwHFefwkIeIcUb7uM3Q48vN04tbdOPaRG1v1ccqN7onGeHIHputmGGgXbh3vO4Outq1KQGSR2eMCTHzrmSldmOkCSEbb0MS84LyYJXWeMMztN7S+02V3bwHvAcmZnG602TsqBcUB114eXugfUWepLVWp1mpXAJ8PLxmrNEzyKcxAUWWztYRhrqIdMjlnsLGEGGzmXzqbPvgHWugL9YsDQc/2QY+GnVM9Wn4WGq96iB63MODlSRUx2iIdTTzHstTZUOnqfeUFknb+9btouvIpKUH9DUsTM9aJGaQYoyEzDzwooM2IrHJEYlo+kq62I0m6kykoFjxnXkKrar86Vc81JZ8+Xgp3RnM6jyGqg+8eQq2kcO9guQzVHrcY7VMsSLaH9GiJOgfrcyKyfdtQsehCYkR0dPtpbuPARFDzT8NafCqM=
    - secure: r74ioIWEn+DKZkWF0gVH9q0VrzuAAIxyrUgjtBj1HuIialKLgrqF+GdhKY9URB7wi8zV0Xy3cSo9f09KVZFW6rZbOUoaZ+bqhHSYSEeL3GLYPW47DWmhN9s32vZpBVIHJCMhWqpudtG9ep1fgjuqGmdVlQW4oT/gSCKi2HHn5BMH7fFeXPxyNMXXBvlwkPY7tdQZ6e8q3ONtEtMAmgzvw3MEslRtxmdiEnukF4FIdSNw2dXzJW4V+JOtUsz5axH+3n8b87G313KBCFJp5s92km+vwr5YYvfcUL+SH9I/pn3AuBwJSoO9smWFDiSqBpHNRJjFv8yd9+NVnRo9n0IotpzEUtGKpkU2mOzHcY/c85ZPMriVku2xXdbwAD25Ufjv5Mpi11G+uzhuo0R/ZPpvvQvQ5aXxiO863qpwi6gfLlDBcN3kQzCitevPkihnsqV8FbDmKYcP5HoTwD+vmfUv07baP+hWwyMrLNbhWtkXr5LDHLf1/eLM2OSV7V8tmBYGCzs0B1x4nMnpE4vUQFNFTw8yuaRyITgAjrByQEMncxlML3eX4giYQVIV3Q50rVlkpS7Hw3uhw36VBwERxsoJ+a5ZmltTd7VqElswwtJ/JN3vqI9j/FJGcKIG8KVSGsHVmkviDeOQIcbtossoDG1tzrX9H0jWOcEXMHLphB349Po=
    - secure: qdYDE8ZOrMoFGyHUmFluMUh2ghsAiMe66dPuZEWJDAqIKzmTSqf0A1MBUbbj2sm6eYHZdMqmQJwDLLpXoFZ0Rur8u9zRbVDUEXqEtnuZ4oepa+8ApEFTmMf0urBNUiXEJTGSOb0evvc6lZHo3WEktB0TSCsXz47MaHjZvEFBQUiCLVtzFOQ5rEdlK45tmrAT1ToBzJ74sLANInAW1Ekx54to/XTTW+ZtaYxdEYVni4DA4xUIDaRcp6PxCywzHiPggpI+Zq4tZfWvIHDr4giz7Jl7PeNDdzYu+ntLrATSb1CR4uA9U27actmlyk6+lFEag3r5HBUknsrLnbMBGi/H+jURaks1xsJnO8kTt0R+5jFpzNSZK/d6C1MXZhknR4JaR5tCzgtKMHNUyaMNTwDdDAlrUON0YtpQ1YTdtpYUKWWosFjOTqZ35YDbz22EgYUIPylVp3kpI7SdvUZIMa5iFZcap17NcShbB9eC3TF0gcUZIAuqgzglro0dSh8VFC7Eg2RXamQIWYsMceR/BDmX5VQyGgKWhoAXlelkMfUn16Evw4eaA0CD098NtBHXhxdZj3Lu91IW0moGAlGDuSrIxl/PqXn90hYYeDroTCE+bY50F2r2Vk4u8in7Pc92rKrKuhgf8iy+ppRdBHqNX7nVScLsFRIPm53RrB8OE3ugD68=
