language: node_js
node_js:
  - 14
script:
  - npm run generate
before_deploy:
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
    -in deploy/deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - echo -e "Host ${DEPLOY_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --quiet --delete ${TRAVIS_BUILD_DIR}/dist/ ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIRECTORY}
  on:
    branch: master
env:
  global:
    - secure: Pq+UlSyQIWWdcTi5Ig+bNbLYYppLcLCcyqAiCwh+0lXlk5Leg4VfZ26osFZqoFVdXl96xpxTUVP4+YTDl291dtKpi+pORWFQu5ta1HZ/b2plgfV8tim6jTH4QMxXYXDUpTLf6/FMfCUImz+ZvhcHoF4N8FrUqnzXx+iTOTxERWboUVBhkpOYS2cq/mhEbWyMS+xN8UVdE+4JH5AGpbsrIrjzIxP0SLKEMlCCEngB+JA9YtQBGqjFqKa1Er1QF9wkc1SDnm+4rEWVNXGrrbgfDRQRZQiuz1cPgKz5LO8cGc8Q5mdSmiVuIcmEmxtJN1fskBZ3ZMQmT6TTmU4h6ft236DKQBhJzNxGgiAxU0otPDbP+Lv2kbp3Xih32arxsng/+JWBr/Ejizg51k0V6wKO7wlGjIwUu/Oz5ppBzVcdzXNYD3Af/EKdIFIMEarJcC3hLlXOJLj1ChSYlheFbHqds6QOHjWgZzv8VQ7Rn7i+cQhJcx+bQeuGg4FDf6DlnE7JiZgaW6qAcXAvh75OtiNbJS5KwKrXsK7GYgh3+se6Pa3zAPWlWTr1KLyqh+Je1BX7K0AT4MFnwQOt3x+PZZUkcsj1y9sgBiMqnDSB0k92dC1zUl9X4ukMR7McDTW1hWnrQN8RLkMubpbFv/yvJPAAI7oQpCndDreToTe59hrRDN8=
    - secure: DstKZh03SpU9ze4cBn7FZik0YDthjUppuAz9BPXN8/vvZe7L1gUqGZqmijm8Z4/3SKm1UpgiU5JqJ2flVNWYR8cDbDtgRqZ5QifJI8JQfy7FBMPPPjkgA3EbUNZUlAvZS4YCYdQVuIIZVozamC2r7ec/Qr/8TNjXOC0NoLQOn+ZqyOz5A54+AcVhgfXy47bCnx11a9U4EfSuaPIwHhwRjPgNbPro3N0EODT7jSkk1mCMzhGSgkuUX2Mtmpx7W3H7isaX2VzUrRLLdnyYpI/hQkVJe9J2snx+aXG/j+i+c2mPtDVcmsmuLImYpxd0xLW/v0VeuadQWgWZ5K2G6Ke9unlEgFWzi97sPIt8Itty+VPdm0b8a9I5Zn4GkE+OfsXJfnH/si88sE2t5XrH6UtjTP1eZ+E2XTIrEXhejgr/wtz1DBllMRtTfFGCTBXVEgs4MBjNSrpAU8O4f4lk+3jMrhknlrXlUUdOQy2L5HwD+nF4jGB7sV1LjnDK8qmpuGTn88kHnFsLV4sKV6Iuw/zjO5nbor9wqUHagBN9JJSeA9NkRDPxarQWrXL0zxO1T9zUArOKKtdUoqbLpfmIzDx3vJzpITgKryVaTrPDD6UtFTZIQXYwbnW+gdfSH2DSBji0Hc/qkZb98NWUrSdZit7oIiczAn9c4mRNZNp3I5o/i2I=
    - secure: lEzkXc6yWOE2IHK813wmExVjl+qS8T+4hfYMhynGguJfXaSsWITBeL5YDDy4YOYDq5xTpvi/PAeHtvoVmnUclu4f9kgGNZP9zHvW/ZBpadBqV1crAQ4FIYahwOMD6LZW9o7TVepXII0KsvNc+EuKsHJWQvoQLxrFkelZulwyZko45lRMExthudyiCgbEQFBD+aKR26tKc8XsKV8O/hK2CijGn+TDxPmjgieZjfXG4peud5863JN+R+8eN+YNjhHiin3FJX3Yx8PSN0+TSwtdEk9gCaFmxfcaBzhd6gl1psBtRbXe9tjLjAYs2ElkBCqIQCAZQhbgBPaMvMWH+U62KcPiVulO+diqkYFWGQ3XVdAZeNYEG5f4p2eLt6fb34v051KF23yfbMriS1RICcGbfcJ2Q7b1jmDOGnNVaHLXgkXtiIwee7HtnjeBVKzl+qQWE7WTLcCbNxLIB0pD2rjJ2lB3lvAJfQAAoDEtq5gNoU+awAbwlV6NSyV3yg2fcxPxGc4dSi/VuG7hwvoCKHFVbO/Em4DqNozLnXbZo60Uoj1A22pR57PalNhmAE6bAIL0/Nqmt6LgqyCw2LqMPpurI/nGlR1WJKCyeU4iz92Xp1wqBPcOrYgR74K7jPZa2kRgq9oJwxLcMqrMPVxINJLv+ZFYwluPc2yvzCKYWfSr51Y=
