name: Node.js CI

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'
    - name: Build the webpage
      run: npm run export
    - name: Deploy to server
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete
        path: ${{ env.GITHUB_WORKSPACE }}/dist
        remote_path: ${{ secrets.REMOTE_PATH }}
        remote_host: ${{ secrets.REMOTE_HOST }}
        remote_user: ${{ secrets.REMOTE_USER }}
        remote_key: ${{ secrets.REMOTE_KEY }}
